### ISSUE TITLE
A workaround for repeat.for and paper-tabs, paper-menu, iron-selector, paper-listbox...

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [roguePanda/aurelia-polymer#23]
When you have a trouble with paper-tabs, paper-radio-button, paper-menu, paper-listbox... anything that uses  iron-selector inside to select an item, try this workaround.

_iron-selector_ selects one from child elements but ignores child child elements inside a child element. (It seems not always, though.)

In the following example, the _<paper-tab>_ is sometimes ignored because it is not a direct child element of the _<paper-tabs>_.

```
 <paper-tabs>
    <div>
      <paper-tab>tab 0</paper-tab>
    </div>
 </paper-tabs>
```

When you use _repeat.for_, Aurelia wraps things in a _<template>_ element. So, no generated element can be selected. (See #17 for more detail.)

A workaround is _au-select_ attribute that gathers all child elements and child child elements under _<iron-selector>_ or similar elements.

In the following example,  paper-tabs works _au-select_ with _<div>_.
Give _selectable="CSS selector"_ to _iron-selector_ and give _class="CSS selector"_ to selectable elements.  (note: \* selectable=".selectable_item" requires ".")

```
      <paper-tabs au-select selectable=".selectable_item">
        <div>
          <paper-tab class="selectable_item" repeat.for="item of items">${item}</paper-tab>
        </div>
      </paper-tabs>
```

This is a TypeScript version of  the _au-select_ custom attribute.

```
// resources/au-select-custom-attribute.ts
//    add  aurelia.use.plugin('resources/au-select-custom-attribute') to main.ts
import { autoinject } from 'aurelia-framework';

@autoinject
export class AuSelectCustomAttribute {
    constructor(private element: Element) {
        (<any>element)._updateItems = function() {
            //var nodes = (<any>window).Polymer.dom(this).queryDistributedElements(this.selectable || '*');
            var nodes = (<any>window).Polymer.dom(this).querySelectorAll(this.selectable || '*');
            nodes = Array.prototype.filter.call(nodes, this._bindFilterItem);
            this._setItems(nodes);
        }
    }   
}
```

This is a JavaScript version.

```
// resources/au-select-custom-attribute.js
//    add  aurelia.use.plugin('resources/au-select-custom-attribute') to main.js
//import {inject} from 'aurelia-framework';

export class AuSelectCustomAttribute {
    constructor(element) {
        element._updateItems = function() {
            //var nodes = window.Polymer.dom(this).queryDistributedElements(this.selectable || '*');
            var nodes = window.Polymer.dom(this).querySelectorAll(this.selectable || '*');
            nodes = Array.prototype.filter.call(nodes, this._bindFilterItem);
            this._setItems(nodes);
        }
    }   
}
```

The above code was borrowed from [PolymerElements/iron-selector#42](https://github.com/PolymerElements/iron-selector/issues/42).

Or, the following code can be added to main.ts to replace the default behavior, if you don't want to use the _au-select_ attribute.

```
export function configure(aurelia: Aurelia) {
  (<any>window).Polymer.IronSelectableBehavior._updateItems = function() {
      //var nodes = win.Polymer.dom(this).queryDistributedElements(this.selectable || '*');
     var nodes = (<any>window).Polymer.dom(this).querySelectorAll(this.selectable || '*');
      nodes = Array.prototype.filter.call(nodes, this._bindFilterItem);
      this._setItems(nodes);
    }
```

**Comment by bnavetta** [comment]
This is great, thanks! Would you mind opening a PR to add the code replacing the default behavior and/or the au-select attribute?

**Comment by HIRANO-Satoshi** [comment]
Okay, I will try.

**Comment by HIRANO-Satoshi** [comment]
Today paper-tabs and repeat.for work without au-select. I can't reproduce the issue and I'm confused.

**Comment by HIRANO-Satoshi** [comment]
Here is a simple skeleton of selection with repeat.for. 

Although this is an example of _paper-dropdown-menu_, the pattern is common to others such as _paper-tabs_.

It shows a list of country names. You will have _countryCode_ after selection.
If you set a country code to the _countryCode_, the country is pre-selected.

```
      <paper-dropdown-menu label="Country" >
        <paper-listbox class="dropdown-content"
              selected.two-way="countryCode" attr-for-selected="id" au-select selectable=".item">
          <div>
             <paper-item repeat.for="data of countryData" id.bind="data.alpha3" class="item">
                  ${data.name}
              </paper-item>
           </div>
        </paper-listbox>
      </paper-dropdown-menu>
```

```
export class MyViewModel {
    countryData: any = [
          {alpha3: 'BHR', name: 'Bahrain'},
          {alpha3: 'JPN', name: 'Japan'}, 
          {alpha3: 'HUN', name: 'Hungary'}
   ];
   countryCode: string = 'JPN';    // pre-selection
}
```

**Comment by bnavetta** [comment]
Hmm, was there an Aurelia upgrade?

**Comment by HIRANO-Satoshi** [comment]
I have just sent a PR. Please merge it, if it is good.

**Comment by bnavetta** [comment]
Merged!

**Comment by wc-matteo** [comment]
It's not working for me (I'm using fd482e6ce9295ed240def186f3214a18e27e6697):

```
Unhandled rejection Error: Error invoking AuSelectCustomAttribute. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: key/value cannot be null or undefined. Are you trying to inject/register something that doesn't exist with DI?
```

I checked and `_aureliaFramework.Element` in [au-select-custom-attribute.js](https://github.com/roguePanda/aurelia-polymer/blob/fd482e6ce9295ed240def186f3214a18e27e6697/dist/amd/au-select-custom-attribute.js#L24) is, in fact, `undefined`...

### markup

``` html
<paper-dropdown-menu>
    <paper-listbox class="dropdown-content" selected="0" au-select selectable=".item">
        <div>
            <paper-item repeat.for="i of 10" class="item">${i}</paper-item>
        </div>
    </paper-listbox>
</paper-dropdown-menu>
```

**Comment by bnavetta** [comment]
Should've been fixed by #25

**Comment by wc-matteo** [comment]
I'm using the latest commit and it's not fixed... now that I notice, the files in `/dist` haven't been updated with the fix, right?

**Yep, that was it. Building the source fixes it.**

**Comment by wc-matteo** [comment]
After some testing I must say that _this_ is not a good workaround...

In the case of `paper-tabs` the added `<div>` interferes with Polymer styles.
Trying to change the bound collection of a `paper-listbox` programmatically doesn't work (the elements stop being selectable).

The only good solution I found at the moment is to use Polymer's own repeater:

``` html
<paper-tabs>
  <template is="dom-repeat" items.bind="items">
    <paper-tab>{{item}}</paper-tab>
  </template>
</paper-tabs>
```

**Comment by HIRANO-Satoshi** [comment]
@wc-matteo, I confirmed your code works. It solves some annoying issues such as font size of tabs in the original workaround. Great invention.

I am not familiar with Polymer's data biding. How do you use it with Aurelia's data binding?

For example, a tab includes <a> tag usually.  With the following code, _item.title_ appears in the tabs, but does not work as a link.

```
<paper-tabs>
  <template is="dom-repeat" items.bind="router.navigation">
    <paper-tab link>
      <a href.bind="item.href">{{item.title}}</a>
    </paper-tab>
  </template>
</paper-tabs>
```

**Comment by wc-matteo** [comment]
@HIRANO-Satoshi 

All credits go to: https://github.com/aurelia/binding/issues/262

I'm not familiar with Polymer's data binding myself, but I found [this](https://www.polymer-project.org/1.0/docs/devguide/data-binding#anatomy-of-a-data-binding).

In short, the syntax is: `<a href$="{{item.href}}">`. Strangely, in this case the attribute (i.e. href) is attached to the _autogenerated_ parent `div` (i.e. `<div class="tab-content style-scope paper-tab">`) in the final rendering.

**Comment by HIRANO-Satoshi** [comment]
I tried the _href$="{{item.href}}"_ and confirmed it does not work.

The fact you found is strange.
